# This is the composite action:
#   https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: Setup Node, pnpm and install dependencies
description: Setup pnpm and Node.js with caching

inputs:
  run-install:
    description: 'Whether to run `pnpm install`'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3
      with:
        run_install: false

    - name: Setup Node
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version-file: .nvmrc
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml

    - name: Install dependencies
      if: ${{ inputs.run-install == 'true' }}
      run: pnpm install --frozen-lockfile
      shell: bash
