version: v1

labels:
  - label: 'enhancement'
    sync: true
    matcher:
      title: '^feat(\(\w+\))?: .*'

  - label: 'bug'
    sync: true
    matcher:
      title: '^fix(\(\w+\))?: .*'

  - label: 'refactor'
    sync: true
    matcher:
      title: '^refactor(\(\w+\))?: .*'

  - label: 'documentation'
    sync: true
    matcher:
      title: '^docs(\(\w+\))?: .*'

  - label: 'test'
    sync: true
    matcher:
      title: '^test(\(\w+\))?: .*'

  - label: 'build'
    sync: true
    matcher:
      title: '^(ci|build)(\((?!release)\w+\))?: (?!.*\brelease\b).*'

  - label: 'release'
    sync: true
    matcher:
      branch: '^release/.*'

  - label: 'dependency'
    sync: true
    matcher:
      title: '^deps(\(\w+\))?: .*'
      branch: '^renovate/.*'
 
checks:
  - context: 'Semantic Pull Request'
    description:
      success: Ready for review & merge.
      failure: Missing semantic label for merge.
    labels:
      any:
        - enhancement
        - bug
        - refactor
        - documentation
        - test
        - build
        - dependency
        - release