version: v1

labels:
  - label: 'bug'
    sync: true
    matcher:
      title: '^fix(\(\w+\))?: .*'

  - label: 'build'
    sync: true
    matcher:
      title: '^(ci|build)(\((?!release)\w+\))?: (?!.*\brelease\b).*'  

  - label: 'chore'
    sync: true
    matcher:
      title: '^chore(\((?!deps)\w+\))?: .*'

  - label: 'dependency'
    sync: true
    matcher:
      branch: '^renovate/.*'
      files: ['pnpm-lock.yaml']

  - label: 'documentation'
    sync: true
    matcher:
      title: '^docs(\(\w+\))?: .*'

  - label: 'enhancement'
    sync: true
    matcher:
      title: '^feat(\(\w+\))?: .*'

  - label: 'refactor'
    sync: true
    matcher:
      title: '^refactor(\(\w+\))?: .*'

  - label: 'release'
    sync: true
    matcher:
      branch: '^release/.*'

  - label: 'test'
    sync: true
    matcher:
      title: '^test(\(\w+\))?: .*'
 
checks:
  - context: 'Semantic Pull Request'
    description:
      success: Ready for review & merge
      failure: Missing semantic label for merge
    labels:
      any:
        - enhancement
        - bug
        - refactor
        - documentation
        - test
        - build
        - release
        - chore
        - dependency