changelog:
  exclude:
    labels:
      - release
  categories:
    - title: 🚀 Features
      labels:
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 🧼 Code Refactoring
      labels:
        - refactor
    - title: 📚 Documentation
      labels:
        - documentation
    - title: 🧪 Testing
      labels:
        - test
    - title: 🏗️ Build System
      labels:
        - build
    - title: 📦 Dependency Updates
      labels:
        - dependency
    - title: 🧹 Chore
      labels:
        - chore
    - title: Other Changes
      labels:
        - '*'
