#import './common.graphql'

query FetchIssueByNumber(
  $owner: String!
  $name: String!
  $number: Int!
  $lastComments: Int
  $firstLabels: Int
) {
  repository(owner: $owner, name: $name) {
    issue(number: $number) {
      ...IssueDetails
    }
  }
}

fragment IssueDetails on Issue {
  __typename
  number
  title
  url
  state
  stateReason
  milestone {
    ...MilestoneFields
  }
  author {
    ...AuthorFields
  }
  comments(last: $lastComments) {
    totalCount
    nodes {
      url
      author {
        ...AuthorFields
      }
      reactions {
        totalCount
      }
      reactionGroups {
        ...ReactionGroupFields
      }
    }
  }
  labels(first: $firstLabels) {
    nodes {
      ...LabelFields
    }
  }
  issueType {
    name
    color
  }
  parent @gated(requires: "subIssues") {
    number
    title
    url
  }
  subIssuesSummary @gated(requires: "subIssues") {
    total
    completed
    percentCompleted
  }
  reactions {
    totalCount
  }
  reactionGroups {
    ...ReactionGroupFields
  }
}
