name: 🐛 Bug Report
description: Report errors or unexpected behavior
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: 🔍 Is there already an issue for your problem?
      description: |
        Thanks for taking the time to fill out this bug report 🤗
        Make sure there aren't any open/closed issues for this topic 😃
      options:
        - label: I have checked older issues, open and closed
          required: true

  - type: textarea
    attributes:
      label: 📝 Description
      description: List steps to reproduce the error and details on what happens and what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🪜 Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: dropdown
    id: environment-version
    attributes:
      label: Gitify Version
      description: What version of Gitify are you using?
      options:
        - 5.8.0
        - 5.7.0
        - 5.6.0
        - 5.5.0
        - 5.4.0
        - 5.3.0
        - 5.2.0
        - 5.1.0
        - 5.0.0
        - 4.6.1
        - Other
    validations:
      required: true

  - type: dropdown
    id: environment-os
    attributes:
      label: Operating System
      description: What OS are you using?
      options:
        - macOS
        - Windows
        - Linux
        - Other
    validations:
      required: true

  - type: dropdown
    id: environment-github
    attributes:
      label: GitHub Account
      description: What GitHub account type are you using?
      options:
        - GitHub.com
        - GitHub Enterprise
        - Combination
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📸 Screenshots
      description: Place any screenshots of the issue here if needed
    validations:
      required: false
