name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  lint:
    name: Lint App
    uses: ./.github/workflows/lint.yml
    permissions:
      contents: read

  tests:
    name: Tests
    uses: ./.github/workflows/test.yml
    needs: lint
    permissions:
      contents: read
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    name: Build
    uses: ./.github/workflows/build.yml
    needs: tests
    permissions:
      contents: read
    secrets:
      OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
      # Signing certificates
      CSC_LINK: ${{ secrets.CSC_LINK }}
      WIN_CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      WIN_CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}
