name: Publish

on:
  workflow_call:
    secrets:
      OAUTH_CLIENT_ID:
        required: true
      # Signing certificates
      CSC_LINK:
        required: true
      WIN_CSC_LINK:
        required: true
      CSC_KEY_PASSWORD:
        required: true
      WIN_CSC_KEY_PASSWORD:
        required: true
      # macOS specific
      APPLE_ID_USERNAME:
        required: true
      APPLE_ID_PASSWORD:
        required: true
      APPLE_ID_TEAM_ID:
        required: true
  workflow_dispatch: # For manually running release process to verify code-signing of artifacts

permissions: {}

jobs:
  prepare:
    name: Prepare draft release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          persist-credentials: false

      - name: Parse release branch
        if: startsWith(github.ref, 'refs/heads/release/')
        run: |
          # Extract the branch name (e.g. release/v1.2.3[-meta])
          ref=${GITHUB_REF#refs/heads/}
          echo "RELEASE_BRANCH=$ref" >> "$GITHUB_ENV"
          # Also export a RELEASE_TAG by removing the `release/` prefix (keeps leading 'v')
          tag=${ref#release/}
          echo "RELEASE_TAG=$tag" >> "$GITHUB_ENV"
        shell: bash

      - name: Create draft release
        run: |
          gh release create "${RELEASE_TAG}" \
            --title "${RELEASE_TAG}" \
            --draft \
            --notes "# <img src=\"https://github.com/gitify-app/gitify/blob/3554605d32a6c08a3d4ec17b02b90e2dd276a152/assets/images/tray-active%402x.png\" /> Gitify ${RELEASE_TAG}" \
            --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ env.RELEASE_TAG }}

  release:
    name: Publish ${{ matrix.platform }} [electron-builder]
    needs: prepare
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: macOS
            package-cmd: pnpm package:macos --publish onTagOrDraft
            artifact-name: Gitify-release-mac
            use-apple-notarization: true
          - os: windows-latest
            platform: Windows
            package-cmd: pnpm package:win --publish onTagOrDraft
            artifact-name: Gitify-release-win
            use-apple-notarization: false
          - os: ubuntu-latest
            platform: Linux
            package-cmd: pnpm package:linux --publish onTagOrDraft
            artifact-name: Gitify-release-linux
            use-apple-notarization: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Build application
        run: pnpm build
        env:
          OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}

      - name: Package and publish for ${{ matrix.platform }}
        run: ${{ matrix.package-cmd }}
        env:
          # Signing certificates - important to use the correct cert per platform
          CSC_LINK: ${{ matrix.platform == 'macOS' && secrets.CSC_LINK || (matrix.platform == 'windows' && secrets.WIN_CSC_LINK || '') }}
          CSC_KEY_PASSWORD: ${{ matrix.platform == 'macOS' && secrets.CSC_KEY_PASSWORD || (matrix.platform == 'windows' && secrets.WIN_CSC_KEY_PASSWORD || '') }}
          # macOS specific
          APPLE_ID_USERNAME: ${{ secrets.APPLE_ID_USERNAME }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_ID_TEAM_ID: ${{ secrets.APPLE_ID_TEAM_ID }}
          NOTARIZE: ${{ matrix.use-apple-notarization }}
          # General
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ matrix.artifact-name }}
          path: |
            dist/*
            !dist/*/
          overwrite: true
