name: Renovate

on:
  push:
    branches:
      - main
    paths:
      - renovate.json
  pull_request:
    paths:
      - renovate.json

permissions:
  contents: read

jobs:
  renovate-config-validator:
    name: Config validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup-node
        with:
          run-install: "false"

      - name: Install Renovate
        run: pnpm install --global renovate

      - name: Validate Renovate config
        run: renovate-config-validator
