name: Renovate

on:
  push:
    branches:
      - main
    paths:
      - renovate.json
  pull_request:
    paths:
      - renovate.json

permissions: {}

jobs:
  renovate-config-validator:
    name: Config validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          sparse-checkout: |
            renovate.json
            .github

      - uses: ./.github/actions/setup-node
        with:
          run-install: 'false'

      - name: Install Renovate
        run: pnpm install --global renovate

      - name: Validate Renovate config
        run: renovate-config-validator
