name: Homebrew

on:
  push:
    tags: 'v*'

jobs:
  pr-to-homebrew:
    runs-on: macos-latest
    steps:
      - uses: Homebrew/actions/setup-homebrew@master
      - id: version
        run: echo "version=$(echo ${{ github.ref }} | sed 's/refs\/tags\/v//')" >> $GITHUB_OUTPUT
      - run: brew bump-cask-pr gitify --version=${{ steps.version.outputs.version }} --message="Bump gitify to ${{ steps.version.outputs.version }}"
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GH_TOKEN }}
