name: Validators

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  pr-lint:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;
            const regex = /^(?<type>build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|deps)(?<scope>\([\w\-\/]+\)?((?=:\s)|(?=!:\s)))?(?<breaking>!)?(?<subject>:\s.*)?/gm;
            const match = regex.exec(title);

            if (!match) {
              core.setFailed('Invalid PR title');
            }
            if (!match.groups.type && !match.groups.subject) {
              core.setFailed('Missing type and subject in PR title');
            }
            if (!match.groups.type) {
              core.setFailed('Missing type in PR title');
            }
            if (!match.groups.subject) {
              core.setFailed('Missing subject in PR title');
            }

  renovate:
    name: Validate Renovate config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - uses: pnpm/action-setup@v3
        with:
          run_install: false
      - run: pnpm install --global renovate
      - name: Validate Renovate config
        run: renovate-config-validator
